#!/usr/bin/env bash

# Collect information from the host

#################################################################################################
# Helper Functions
#################################################################################################
function execute_collector_modules() {
  # Source all test/modules and exclude this main script
  for collector_module in $(find ./collector/modules/ -type f ) ; do
    . ${collector_module} # Run each test found
  done
}


function display_collector_header() {
  echo "======================================================================="
  echo "Starting data collector"
  echo "======================================================================="
}

function display_collector_end() {
  echo "======================================================================="
  echo "Data collector completed"
  echo "======================================================================="
}

# Remove zero length files from the output directory
function collector_remove_empty_files() {
  if [ ${OPT_VERBOSITY} -ge 2 ]; then
    debug_msg "Removing empty files from ${OUTPUT_PATH}"
    find ${OUTPUT_PATH} -type f -empty -delete -print
  else
    find ${OUTPUT_PATH} -type f -empty -delete
  fi
}

# Cleanup routine
function collector_cleanup() {
  unset IFS
  collector_remove_empty_files
}

#################################################################################################
# Main 
#################################################################################################

# Run the individual collectors
display_collector_header
execute_collector_modules
collector_cleanup
display_collector_end
